version: '3'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

  node-learning:
    image: public.ecr.aws/j2y4l3f1/node-learning:latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongodb:27017/testdb?authSource=admin&w=1
      DOMAIN: http://localhost:3000
      SHORT_LINK_EXPIRE_DURATION: 1800

volumes:
  mongo-data:
    driver: local
    