version: '3'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb

  node-learning:
    image: public.ecr.aws/j2y4l3f1/node-learning:latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/testDB
      DOMAIN: http://localhost:3000
      SHORT_LINK_EXPIRE_DURATION: 1800

volumes:
  data-volume:
    